---
language: ruby
rvm:
- 2.3.1
- 2.4.1
before_install: gem install bundler -v 1.11.2
deploy:
  provider: rubygems
  api_key:
    secure: ZOvsryo3ZRUom+YBwpYrqLOQ8Sa/BSmp3igu4k5RcLOIVYwGgN1lLgeleKvFJHbuPwauFOdD3XsoOiHHM6D4d1YvgmSuQROU4Z4zyuGb2vnnAxhvwTvFjecSKVJk+mcvel1EjP+Az0UH2Oom3Dctp+oCpdtJQ3D0tDmvHmJhRQOQJcAhwiXKUMadF6vWvmzHkkaYfxUIwh+Bd5gna2tSImPdX6E4MPba0Lpi+Afhl4Xu3OSRGx4q2NFPrdqqRJj4dqASXREP562VBiiSBvZR/c+2E5MDSUK4J6aUTxaRQKYXN5tDsiXFW6FLc77KS2jYXxPZSsktP80Ms1BYhr1W8pWKBFEJW96uShrIYbyWdkYjqozPShxMl84+cTl+UqtmE7TJSVZClGBz2b1qUgtME2IAjMElR9a/qwCfHzltqitSWvlEvdWrHgd8iIkTuBCKYBgTQeS++zFWLvIOdDSiAHGOE0w2bTL2c53viBn1cRYYpMJR8kOBRjipytBjqzWXQGQi1WYmpD8+J03KHzSCfZolZBqeClcaL2e2ggEaWUH4FIyVk2Df5Rs5MQwXwrb3mFnddetRTHGBhONv1SJ43uBbe/F1y7HVPJeW2/1gg3Gfj4iw/9kdq+KjHJEETQJXVXaKAMiDfzXfNfkLBk8RgLFepfIp13F38myMCWnvtyg=
  gem: tableschema
  on:
    tags: true
    repo: frictionlessdata/tableschema-rb
